services:
  initcloud_nginx:
    image: floodnut/nginx
    container_name: initcloud_nginx
    environment:
      - TZ=Asia/Seoul
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - initcloud_board
      - initcloud_scanner
    restart: always
  initcloud_board:
    image: floodnut/initcloud_board
    container_name: initcloud_board
    env_file:
     - .env
    environment:
     - TZ=Asia/Seoul
    ports:
     - ${BOARD_PORT}:80
    depends_on:
     - initcloud_scanner
    restart: always
  initcloud_db:
    image: floodnut/initcloud_db
    container_name: initcloud_db
    env_file:
     - .env
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./db/data:/var/lib/mariadb:rw
    ports:
      - ${DB_PORT}:3306
    restart: always
  initcloud_parser:
    image: floodnut/parser_api
    container_name: initcloud_parser
    ports:
      - ${PARSER_PORT}:8000
    env_file:
     - .env
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./backend_scanner/uploads:/app/uploads
    restart: always
  initcloud_scanner:
    image: floodnut/scanner_api
    container_name: initcloud_scanner
    ports:
      - ${SCANNER_PORT}:8080
    env_file:
     - .env
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mariadb://initcloud_db:3306/initcloud
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./backend_scanner/uploads:/app/uploads
    restart: always
    depends_on:     
     - initcloud_db
     - initcloud_parser
